### ISSUE TITLE
5800x X570打算基于你这个版本修改下

### ISSUE THREAD

**Issue by mrdear** [joe-zhang3/hackintosh#2]
5800X有什么特别注意的吗?

**Comment by joe-zhang3** [comment]
没什么特别注意的。就是kernal-patch去拿最新的。https://github.com/AMD-OSX/AMD_Vanilla/tree/opencore/17h_19h。 X570应该跟我的差不多，就是把ACPI里的SSDT-CPUR去掉，因为我是B550M主板。

**Comment by mrdear** [comment]
搞定了,基本都正常,可以参考下.

https://github.com/mrdear/Ryzen-5800x-X570-AORUS-PRO-WIFI-OC0.6.4
